infer_config {
  unique_id: 1
  gpu_ids: 0
  max_batch_size: 1
  backend {
    triton {
      model_name: "fasterrcnn"
      version: -1
      model_repo {
        root: "./models"
        strict_model_config: true
      }
    }
    output_mem_type: MEMORY_TYPE_CPU
  }

  preprocess {
    network_format: IMAGE_FORMAT_RGB
    tensor_order: TENSOR_ORDER_NHWC
    tensor_name: "inputs"
    maintain_aspect_ratio: 0
    normalize {
      scale_factor: 1.0
      channel_offsets: [0, 0, 0]
    }
  }

  postprocess {
    labelfile_path: "./models/fasterrcnn/labels.txt"
    detection {
      num_detected_classes: 2
      custom_parse_bbox_func: "NvDsInferParseCustomTfFRCNN"
      nms {
        confidence_threshold: 0.5
        iou_threshold: 0.3
        topk : 20
      }
    }
  }

  custom_lib {
    path: "/opt/nvidia/deepstream/deepstream/lib/libnvds_infercustomparser.so"
  }

}
input_control {
  process_mode: PROCESS_MODE_FULL_FRAME
  interval: 0
}
