infer_config {
  unique_id: 1
  gpu_ids: 0
  max_batch_size: 1
  backend {
    triton {
      model_name: "rtdetr"
      version: -1
      model_repo {
        root: "./models"
        strict_model_config: true
      }
    }
    output_mem_type: MEMORY_TYPE_CPU
  }

  preprocess {
    network_format: IMAGE_FORMAT_RGB
    tensor_order: TENSOR_ORDER_LINEAR
    tensor_name: "input"
    frame_scaling_hw: FRAME_SCALING_HW_DEFAULT
    frame_scaling_filter: 1
    symmetric_padding: 0
    maintain_aspect_ratio: 0
    normalize {
      scale_factor: 0.0039215697906911373
      channel_offsets: [0.0,0.0,0.0]
    }
  }

  postprocess {
    labelfile_path: "./models/rtdetr/labels.txt"
    detection {
      num_detected_classes: 1
      custom_parse_bbox_func: "NvDsInferParseYolo"
    }
  }

  custom_lib {
    path: "/home/siot/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so"
  }
}

input_control {
  process_mode: PROCESS_MODE_FULL_FRAME
  operate_on_gie_id: -1
  interval: 0
}
